Update base-template.yaml

diff --git a/static/infrastructure/base-template.yaml b/static/infrastructure/base-template.yaml
--- a/static/infrastructure/base-template.yaml
+++ b/static/infrastructure/base-template.yaml
@@ -471,51 +471,50 @@ Resources:
             pre_build:
               commands:
                 - echo ">>> build cluster config with Region $AWSRegion"
-                - cat > cluster-config.yaml << EOF
-                  apiVersion: eksctl.io/v1alpha5
-                  kind: ClusterConfig
-                  availabilityZones:
-                    - ${AWSRegion}a
-                    - ${AWSRegion}b
-                    - ${AWSRegion}c
-                  metadata:
-                    name: ${EKSClusterName}
-                    region: ${AWSRegion}
-                    version: "${KubernetesVersion}"
-                  cloudWatch:
-                      clusterLogging:
-                          enableTypes: ["*"]
-                  iam:
-                    withOIDC: true
-                  secretsEncryption:
-                    keyARN: ${KMS_ARN}
-                  managedNodeGroups:
-                    - name: nodegroup
-                      instanceType: ${WorkerNodeInstanceType}
-                      desiredCapacity: 1
-                      minSize: 1
-                      maxSize: 2
-                      privateNetworking: true
-                      volumeSize: 100
-                      volumeType: gp3
-                      volumeEncrypted: true
-                      tags:
-                        'eks:cluster-name': ${EKSClusterName}
-                        'stack-name': ${STACK_NAME}
-                      iam:
-                        withAddonPolicies:
-                          imageBuilder: true
-                          autoScaler: true
-                          externalDNS: true
-                          certManager: true
-                          appMesh: true
-                          ebs: true
-                          fsx: true
-                          efs: true
-                          albIngress: true
-                          xRay: true
-                          cloudWatch: true
-                  EOF
+                - echo "Creating cluster config file"
+                - echo "apiVersion: eksctl.io/v1alpha5" > cluster-config.yaml
+                - echo "kind: ClusterConfig" >> cluster-config.yaml
+                - echo "availabilityZones:" >> cluster-config.yaml
+                - echo "  - ${AWSRegion}a" >> cluster-config.yaml
+                - echo "  - ${AWSRegion}b" >> cluster-config.yaml
+                - echo "  - ${AWSRegion}c" >> cluster-config.yaml
+                - echo "metadata:" >> cluster-config.yaml
+                - echo "  name: ${EKSClusterName}" >> cluster-config.yaml
+                - echo "  region: ${AWSRegion}" >> cluster-config.yaml
+                - echo "  version: \"${KubernetesVersion}\"" >> cluster-config.yaml
+                - echo "cloudWatch:" >> cluster-config.yaml
+                - echo "  clusterLogging:" >> cluster-config.yaml
+                - echo "    enableTypes: [\"*\"]" >> cluster-config.yaml
+                - echo "iam:" >> cluster-config.yaml
+                - echo "  withOIDC: true" >> cluster-config.yaml
+                - echo "secretsEncryption:" >> cluster-config.yaml
+                - echo "  keyARN: ${KMS_ARN}" >> cluster-config.yaml
+                - echo "managedNodeGroups:" >> cluster-config.yaml
+                - echo "  - name: nodegroup" >> cluster-config.yaml
+                - echo "    instanceType: ${WorkerNodeInstanceType}" >> cluster-config.yaml
+                - echo "    desiredCapacity: 1" >> cluster-config.yaml
+                - echo "    minSize: 1" >> cluster-config.yaml
+                - echo "    maxSize: 2" >> cluster-config.yaml
+                - echo "    privateNetworking: true" >> cluster-config.yaml
+                - echo "    volumeSize: 100" >> cluster-config.yaml
+                - echo "    volumeType: gp3" >> cluster-config.yaml
+                - echo "    volumeEncrypted: true" >> cluster-config.yaml
+                - echo "    tags:" >> cluster-config.yaml
+                - echo "      'eks:cluster-name': ${EKSClusterName}" >> cluster-config.yaml
+                - echo "      'stack-name': ${STACK_NAME}" >> cluster-config.yaml
+                - echo "    iam:" >> cluster-config.yaml
+                - echo "      withAddonPolicies:" >> cluster-config.yaml
+                - echo "        imageBuilder: true" >> cluster-config.yaml
+                - echo "        autoScaler: true" >> cluster-config.yaml
+                - echo "        externalDNS: true" >> cluster-config.yaml
+                - echo "        certManager: true" >> cluster-config.yaml
+                - echo "        appMesh: true" >> cluster-config.yaml
+                - echo "        ebs: true" >> cluster-config.yaml
+                - echo "        fsx: true" >> cluster-config.yaml
+                - echo "        efs: true" >> cluster-config.yaml
+                - echo "        albIngress: true" >> cluster-config.yaml
+                - echo "        xRay: true" >> cluster-config.yaml
+                - echo "        cloudWatch: true" >> cluster-config.yaml
                 - cat cluster-config.yaml
                 - echo ">>> install awscli"
                 - pip3 install --upgrade --user awscli
@@ -530,13 +529,14 @@ Resources:
               commands:
                 - echo ">>> creating EKS cluster in region $AWSRegion"
                 - |
-                  if eksctl create cluster -f cluster-config.yaml --region $AWSRegion; then
+                  eksctl create cluster -f cluster-config.yaml --region $AWSRegion
+                  if [ $? -eq 0 ]; then
                     export BUILD_SUCCESS=true
                     echo "EKS cluster creation successful"
                   else
                     echo "EKS cluster creation failed"
                     if [ -n "$WAIT_HANDLE_URL" ]; then
-                      curl -X PUT -H 'Content-Type:' --data-binary '{"Status": "FAILURE", "Reason": "EKS Cluster Creation Failed", "UniqueId": "EKSCluster", "Data": "EKS Cluster Creation Failed"}' "$WAIT_HANDLE_URL"
+                      curl -X PUT -H 'Content-Type:' --data-binary '{"Status":"FAILURE","Reason":"EKS Cluster Creation Failed","UniqueId":"EKSCluster","Data":"EKS Cluster Creation Failed"}' "$WAIT_HANDLE_URL"
                       echo "Sent FAILURE signal to CloudFormation"
                     fi
                     exit 1
@@ -549,7 +549,10 @@ Resources:
                     echo "Signaling CloudFormation with SUCCESS status"
                     echo "WAIT_HANDLE_URL: $WAIT_HANDLE_URL"
                     if [ -n "$WAIT_HANDLE_URL" ]; then
-                      curl -X PUT -H 'Content-Type:' --data-binary '{"Status": "SUCCESS", "Reason": "EKS Cluster Created", "UniqueId": "EKSCluster", "Data": "EKS Cluster Creation Complete"}' "$WAIT_HANDLE_URL" || echo "Failed to send success signal to CloudFormation"
+                      curl -X PUT -H 'Content-Type:' --data-binary '{"Status":"SUCCESS","Reason":"EKS Cluster Created","UniqueId":"EKSCluster","Data":"EKS Cluster Creation Complete"}' "$WAIT_HANDLE_URL"
+                      if [ $? -ne 0 ]; then
+                        echo "Failed to send success signal to CloudFormation"
+                      fi
                     else
                       echo "ERROR: WAIT_HANDLE_URL is not set. Skipping wait condition signal."
                       exit 1
