Update vscode-server.yaml

diff --git a/static/infrastructure/vscode-server.yaml b/static/infrastructure/vscode-server.yaml
--- a/static/infrastructure/vscode-server.yaml
+++ b/static/infrastructure/vscode-server.yaml
@@ -1133,7 +1133,6 @@ Resources:
                     ls -la ${HomeFolder}
                   fi
 
-
   VSCodeK8sSSMDoc:
     Type: AWS::SSM::Document
     Properties:
@@ -1152,26 +1151,19 @@ Resources:
             type: String
             description: "Name of the EKS cluster"
             default: "akuity-aws-cluster"
+          VSCodeUser:
+            type: String
+            description: "VSCode user"
+            default: "vscode"
         mainSteps:
           - action: aws:runShellScript
-            name: InstallKubectl
-            precondition:
-              StringEquals:
-                - '{{ LinuxFlavor }}'
-                - al2023
+            name: ConfigureKubectl
             inputs:
               runCommand:
                 - '#!/bin/bash'
-                - set -e  # Exit on any error
-                - echo "Installing kubectl..."
-                - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
-                - chmod +x ./kubectl
-                - mv ./kubectl /usr/local/bin/kubectl
-                - echo "Kubectl installed successfully."
-                - echo "source <(kubectl completion bash)" >> /home/vscode/.bashrc
-                - echo "alias k=kubectl" >> /home/vscode/.bashrc
-                - echo "complete -o default -F __start_kubectl k" >> /home/vscode/.bashrc
-                - source /home/vscode/.bashrc
+                - echo "alias k=kubectl" >> /home/{{ VSCodeUser }}/.bashrc
+                - echo "complete -o default -F __start_kubectl k" >> /home/{{ VSCodeUser }}/.bashrc
+                - source /home/{{ VSCodeUser }}/.bashrc
   
           - action: aws:runShellScript
             name: ConfigureEKSAccess
@@ -1186,10 +1178,10 @@ Resources:
                 - EKS_CLUSTER_NAME="{{ EKSClusterName }}"
                 - REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/region)
                 - echo "Setting up kubeconfig for EKS cluster: $EKS_CLUSTER_NAME in region $REGION"
-                - mkdir -p /home/vscode/.kube
-                - aws eks update-kubeconfig --name "$EKS_CLUSTER_NAME" --region "$REGION" --kubeconfig /home/vscode/.kube/config
-                - chown -R vscode:vscode /home/vscode/.kube
-                - chmod 600 /home/vscode/.kube/config
+                - mkdir -p /home/{{ VSCodeUser }}/.kube
+                - aws eks update-kubeconfig --name "$EKS_CLUSTER_NAME" --region "$REGION" --kubeconfig /home/{{ VSCodeUser }}/.kube/config
+                - chown -R {{ VSCodeUser }}:{{ VSCodeUser }} /home/{{ VSCodeUser }}/.kube
+                - chmod 600 /home/{{ VSCodeUser }}/.kube/config
                 - echo "EKS kubeconfig setup completed."
   
           - action: aws:runShellScript
@@ -1203,11 +1195,18 @@ Resources:
                 - '#!/bin/bash'
                 - set -e
                 - echo "Installing ArgoCD CLI..."
-                - curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
-                - chmod +x /usr/local/bin/argocd
-                - echo "ArgoCD CLI installed."
-
-
+                - VERSION=$(curl --silent "https://api.github.com/repos/argoproj/argo-cd/releases/latest" | grep '"tag_name"' | sed -E 's/.*"([^"]+)".*/\1/')
+                - curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/download/$VERSION/argocd-linux-arm64
+                - if [ $? -eq 0 ] && [ -f argocd ]; then
+                -   chmod +x ./argocd
+                -   sudo mv ./argocd /usr/local/bin/argocd
+                -   echo "ArgoCD CLI installed successfully."
+                -   argocd version --client
+                - else
+                -   echo "Failed to download ArgoCD CLI."
+                -   exit 1
+                - fi
+  
           - action: aws:runShellScript
             name: SetupArgoCDAccess
             precondition:
@@ -1222,14 +1221,14 @@ Resources:
                   EKS_CLUSTER_NAME="{{ EKSClusterName }}"
                   REGION=$(curl -s http://169.254.169.254/latest/meta-data/placement/region)
                   SSM_PREFIX="/eks/$EKS_CLUSTER_NAME"
-
+  
                   echo "Retrieving ArgoCD details from SSM..."
                   ARGOCD_SERVER=$(aws ssm get-parameter --name "$SSM_PREFIX/argocd-server" --query "Parameter.Value" --output text || echo "Not available yet")
                   ARGOCD_USERNAME="admin"
                   ARGOCD_PASSWORD=$(aws ssm get-parameter --name "$SSM_PREFIX/argocd-password" --with-decryption --query "Parameter.Value" --output text || echo "Not available yet")
-
+  
                   echo "Creating ArgoCD info script..."
-                  cat << 'EOF' > /home/vscode/argocd-info.sh
+                  cat << EOF > /home/{{ VSCodeUser }}/argocd-info.sh
                   #!/bin/bash
                   echo "==================================================="
                   echo "  🚀 ArgoCD Login Details"
@@ -1242,10 +1241,11 @@ Resources:
                   echo "   argocd login $ARGOCD_SERVER --username admin --password \"\$ARGOCD_PASSWORD\" --insecure"
                   echo "==================================================="
                   EOF
+  
+                  chmod +x /home/{{ VSCodeUser }}/argocd-info.sh
+                  chown {{ VSCodeUser }}:{{ VSCodeUser }} /home/{{ VSCodeUser }}/argocd-info.sh
+                  echo "ArgoCD setup completed."
 
-                  chmod +x /home/vscode/argocd-info.sh
-                  chown vscode:vscode /home/vscode/argocd-info.sh
-                  echo "ArgoCD setup completed."  
 
   VSCodeInstanceRole:
     Type: AWS::IAM::Role
